<a href="https://colab.research.google.com/github/AshishRastogi123/Deep_leaning_Practice/blob/main/Nueral_network_from_scrach.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Regression from Scrach

Logistic Regression used in Binary class classification which we used here
Linear are used for multi class classification

In [50]:
import numpy as np
import torch

In [51]:
# Making training data
# where we have imput --> (temp,rainfall, humidity) --> yield of apple and oranges crops
inputs = np.array([
    [73, 67, 43],
    [91, 88, 64],
    [87, 134, 58],
    [182, 43, 37],
    [69, 96, 78],], dtype='float32')

In [52]:
# Target [apple and oranges]
target =np.array([[56, 78],[81, 101],[119, 113], [22, 37],[103, 119]], dtype='float32')

In [53]:
#Convert input and target in tensor
inputs = torch.from_numpy(inputs)
target=torch.from_numpy(target)

print(inputs)
print(target)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [182.,  43.,  37.],
        [ 69.,  96.,  78.]])
tensor([[ 56.,  78.],
        [ 81., 101.],
        [119., 113.],
        [ 22.,  37.],
        [103., 119.]])


In [54]:
#Weights and biases
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2, requires_grad=True)

print(w)
print(b)


tensor([[ 0.4967,  0.5143, -1.5058],
        [-2.0781, -0.8896, -0.2568]], requires_grad=True)
tensor([ 0.0185, -0.0617], requires_grad=True)


In [55]:
# define the model
#apply linear regresiion
def model(x):
  return x @ w.t() +b #where @ denote matrix maltiplication and t() for transpose


In [56]:
w.t()

tensor([[ 0.4967, -2.0781],
        [ 0.5143, -0.8896],
        [-1.5058, -0.2568]], grad_fn=<TBackward0>)

In [57]:
pred = model(inputs)
print(pred)

tensor([[   5.9920, -222.4141],
        [  -5.8868, -283.8956],
        [  24.8210, -314.9662],
        [  56.8232, -426.0402],
        [ -33.7801, -248.8883]], grad_fn=<AddBackward0>)


In [58]:
#that not predict properly
#So we will used loss function
def MSE(y,y_hat):
  diff=y -y_hat

  return torch.sum(diff*diff)/diff.numel()

In [59]:
#Error or loss
loss=MSE(target,pred)
print(loss)

tensor(81013.7500, grad_fn=<DivBackward0>)


In [60]:
# Compute the Gradient
loss.backward() # this function automatically gradient with respect to w and with respect to b which comes from y_hat comes from model function


In [61]:
print(w)
print(w.grad)


tensor([[ 0.4967,  0.5143, -1.5058],
        [-2.0781, -0.8896, -0.2568]], requires_grad=True)
tensor([[ -4570.1699,  -7050.0103,  -4510.7734],
        [-40769.2812, -33314.8047, -21640.1875]])


In [62]:
print(b)
print(b.grad)

tensor([ 0.0185, -0.0617], requires_grad=True)
tensor([ -66.6061, -388.8409])


In [63]:
#reset our gradient
w.grad.zero_()
b.grad.zero_()

tensor([0., 0.])

In [64]:
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [65]:
#Adjest parameter (prams)
pred=model(inputs)
loss=MSE(target,pred)
print(pred)

tensor([[   5.9920, -222.4141],
        [  -5.8868, -283.8956],
        [  24.8210, -314.9662],
        [  56.8232, -426.0402],
        [ -33.7801, -248.8883]], grad_fn=<AddBackward0>)


In [66]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ -4570.1699,  -7050.0103,  -4510.7734],
        [-40769.2812, -33314.8047, -21640.1875]])
tensor([ -66.6061, -388.8409])


In [67]:
learning_rate= 1e-5 # 1*10^-5

with torch.no_grad():
  # Perform in-place updates to w and b
  w.sub_(w.grad * learning_rate)
  b.sub_(b.grad * learning_rate)
  # Now, reset the gradients to zero for the next iteration
  w.grad.zero_()
  b.grad.zero_()

In [68]:
print(w)
print(b)

tensor([[ 0.5424,  0.5848, -1.4606],
        [-1.6705, -0.5565, -0.0404]], requires_grad=True)
tensor([ 0.0192, -0.0578], requires_grad=True)


In [69]:
# Calculate again
preds= model(inputs)
loss= MSE(target, preds)
print(loss)

tensor(51192.7578, grad_fn=<DivBackward0>)


In [71]:
#Training for multiple epoch
for i in range(400):
  preds= model(inputs)
  loss = MSE(target, preds)
  loss.backward()

  # learning_rate= 1e-5 # 1*10^-5

  with torch.no_grad():
  # Perform in-place updates to w and b
    w.sub_(w.grad * learning_rate)
    b.sub_(b.grad * learning_rate)
  # Now, reset the gradients to zero for the next iteration
    w.grad.zero_()
    b.grad.zero_()
  print(f"Epoch: {i/100} and loss : {loss}")

Epoch: 0.0 and loss : 51192.7578125
Epoch: 0.01 and loss : 32562.568359375
Epoch: 0.02 and loss : 20915.22265625
Epoch: 0.03 and loss : 13625.4169921875
Epoch: 0.04 and loss : 9055.2236328125
Epoch: 0.05 and loss : 6182.72119140625
Epoch: 0.06 and loss : 4370.31640625
Epoch: 0.07 and loss : 3220.17822265625
Epoch: 0.08 and loss : 2484.0732421875
Epoch: 0.09 and loss : 2007.0931396484375
Epoch: 0.1 and loss : 1692.556640625
Epoch: 0.11 and loss : 1480.1123046875
Epoch: 0.12 and loss : 1332.074462890625
Epoch: 0.13 and loss : 1224.900146484375
Epoch: 0.14 and loss : 1143.8712158203125
Epoch: 0.15 and loss : 1079.775146484375
Epoch: 0.16 and loss : 1026.8389892578125
Epoch: 0.17 and loss : 981.431640625
Epoch: 0.18 and loss : 941.2654418945312
Epoch: 0.19 and loss : 904.88671875
Epoch: 0.2 and loss : 871.3663940429688
Epoch: 0.21 and loss : 840.1028442382812
Epoch: 0.22 and loss : 810.6993408203125
Epoch: 0.23 and loss : 782.8885498046875
Epoch: 0.24 and loss : 756.4845581054688
Epoch: 0.

In [72]:
# here we start loss at  51192.7578125 to reduce it till the 77.66266632080078
pred=model(inputs)
loss = MSE(target , preds)
print(loss)

tensor(77.6627, grad_fn=<DivBackward0>)


In [73]:
from math import sqrt
sqrt(loss)

/tmp/ipython-input-3167310485.py:2: UserWarning: Converting a tensor with requires_grad=True to a scalar may lead to unexpected behavior.
Consider using tensor.detach() first. (Triggered internally at /pytorch/torch/csrc/autograd/generated/python_variable_methods.cpp:836.)
  sqrt(loss)


8.812642414213842

In [74]:
preds

tensor([[ 60.1253,  69.4059],
        [ 76.9834,  98.5307],
        [135.3792, 119.5272],
        [ 21.8672,  38.9671],
        [ 84.3467, 118.1035]], grad_fn=<AddBackward0>)

In [76]:
target

tensor([[ 56.,  78.],
        [ 81., 101.],
        [119., 113.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
# now we very closed to prediction