In [ ]:
import torch

# Tensor


In [ ]:
t1=torch.tensor(4.) #short hand of 4.0

In [ ]:
t1

tensor(4.)

In [ ]:
t1.dtype

torch.float32

In [ ]:
t2=torch.tensor([1.,2,3,4,5,6])

In [ ]:
t2 # if one value is float it's make all values float

tensor([1., 2., 3., 4., 5., 6.])

In [ ]:
#Matrix
t3=torch.tensor(
    [[1,2],
    [4,5],
    [9,11]]
)
t3

tensor([[ 1,  2],
        [ 4,  5],
        [ 9, 11]])

In [ ]:
#3d tensor
t4=torch.tensor(
    [
       [
        [1,2,3,4],
        [6,3,2,1],
        [9,484,282,2]],
       [
           [3,1,3,1],
           [1,3,5,6],
           [4,4,1,4]
       ]
    ]
)
t4

tensor([[[  1,   2,   3,   4],
         [  6,   3,   2,   1],
         [  9, 484, 282,   2]],

        [[  3,   1,   3,   1],
         [  1,   3,   5,   6],
         [  4,   4,   1,   4]]])

In [ ]:
t3.shape

torch.Size([3, 2])

In [ ]:
t4.shape

torch.Size([2, 3, 4])

# Tensor Operations and Gradients

In [ ]:
#Create tensor
x=torch.tensor(3.)
w=torch.tensor(4. , requires_grad=True) # require_grad=True mean we tell py torch to automatic compute derivative of w in future for
#It's an Pytorch feature
b=torch.tensor(5., requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
# Airthemetic Operations
y=w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
#Compute Derivatives
y.backward()

In [ ]:
#display The value
print("dy/dx : ",x.grad)
print("dy/dw : ", w.grad)
print("dy/db : ", b.grad)

dy/dx :  None
dy/dw :  tensor(3.)
dy/db :  tensor(1.)


# Tensor function

In [ ]:
#Create Tensor with fixed value to every element
t6=torch.full([3,2],0)
t6

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [ ]:
#Create concatinate with tensor
t7=torch.cat([t3,t6])
t7

tensor([[ 1,  2],
        [ 4,  5],
        [ 9, 11],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]])

In [ ]:
#Change the sin of each element
t8=torch.sin(t7)
t8

tensor([[ 0.8415,  0.9093],
        [-0.7568, -0.9589],
        [ 0.4121, -1.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000]])

In [ ]:
# Chage the shape of the Tensor
t9=t8.reshape([3,2,2])
t9

tensor([[[ 0.8415,  0.9093],
         [-0.7568, -0.9589]],

        [[ 0.4121, -1.0000],
         [ 0.0000,  0.0000]],

        [[ 0.0000,  0.0000],
         [ 0.0000,  0.0000]]])

# Interpreotibility with numpy

In [ ]:
import numpy as np
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
y=torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [ ]:
x.dtype, y.dtype

(dtype('int64'), torch.int64)

In [ ]:
z=y.numpy()

In [ ]:
#MNIST dataset another fashion MNIST